# Generated by Django 4.2.6 on 2023-11-01 12:01

from django.db import migrations

import coursesapp.fields


class Migration(migrations.Migration):
    dependencies = [
        ("coursesapp", "0002_video_text_image_file_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="content",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="module",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="content",
            name="order",
            field=coursesapp.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="module",
            name="order",
            field=coursesapp.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
